# Generated by Django 4.2.16 on 2024-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/')),
                ('created_by', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=800)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='files/')),
                ('created_by', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=800)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
