# Generated by Django 4.2.16 on 2025-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='files/')),
                ('creadoPor', models.CharField(max_length=200)),
                ('parrafo', models.CharField(max_length=800)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='files/')),
                ('creadoPor', models.CharField(max_length=200)),
                ('parrafo', models.CharField(max_length=800)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
